name: Release

on:
  workflow_dispatch:

jobs:
  release_create:
    name: (Release) Create release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: npm
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Extract reporter package version
        run: |
          export PKG_VERSION=$(npm pkg get version | sed 's/^["'\'']//; s/["'\'']$//')
          echo "GREENER_PKG_VERSION=$PKG_VERSION" >> "$GITHUB_ENV"

      - uses: actions/setup-node@v6
        with:
          node-version: "latest"

      - run: npm install -g npm@latest

      - run: |
          npm i
          npm pack

      - run: ./build-servermock-native-lib.sh linux-x64 linux-x64

      - name: Prebuild servermock addon
        working-directory: greener-servermock
        run: npx prebuildify --napi --strip

      - name: Pack servermock
        working-directory: greener-servermock
        run: npm pack

      - name: Test
        run: npm test

      - name: Create release
        run: |
          gh release create v${{ env.GREENER_PKG_VERSION }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish reporter
        run: |
          npm publish --access=public ./greener-reporter-${{ env.GREENER_PKG_VERSION }}.tgz
